highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: Soumyajit Deb
email: debsoumyajit100@gmail.com
description: Website of Soumyajit Deb
keywords: Soumyajit Deb, hyp3r5pace, security, developer, geek, programmer, runner, github
baseurl: ""
url: 
name: Soumyaji Deb\'s blog
author:
  name: Soumyajit Deb
  email: debsoumyajit100@gmail.com
